### ISSUE TITLE
Attributed Strings

### ISSUE THREAD

**Issue by sinanku** [AndreasVerhoeven/AvePurchaseButton#4]
Is there a way we could possibly use attributed strings instead of regular for currency formatting?

**Comment by sinanku** [comment]
Found a way around this.  Just use .string after an attributed string to make it a regular string (although the attributed string can be useful for super and subscript formatting in currencies, so I will keep the issue open)

**Comment by AndreasVerhoeven** [comment]
I've just added `attributedNormalTitle` and `attributedConfirmationTitle` as well in 1.0.2 :)

**Comment by sinanku** [comment]
Awesome!  Thank you :)
