### ISSUE TITLE
Setting button colors not observed

### ISSUE THREAD

**Issue by billburgess** [AndreasVerhoeven/AvePurchaseButton#6]
I'm trying to implement this purchase confirm button in my project and the setting of .normalColor and .confirmationColor is not working. The button defaults to the blue and green default colors until progress is started, which adopts the normalColor. Is there a specific order you should set the colors in? The example app doesn't cover changing the colors at all.

**Comment by AndreasVerhoeven** [comment]
Good catch! The colors are now correctly updating the button appearance directly with version 1.0.5.
